### ISSUE TITLE
Alphabetize /requests list

### ISSUE THREAD

**Issue by rmichela** [salesforce/oss-request#38]
When viewing the list of requests, I would like the list to be alphabetized so I can easily find a specific request in the list.

**Comment by jamesward** [comment]
Three ways to handle this:

1. Just sort it alphabetically (Easy)
2. Enable user sort options (most recent, create date, status, name, etc) (Medium)
3. Add a user search (Medium)

WDYT?  Want to write some Scala?  Let's pair program it. :)

**Comment by rmichela** [comment]
I would start with sorting alphabetically.
