### ISSUE TITLE
Ask timed out on [Actor[akka://application/user/$a#-1415981005]] after [15000 ms]. Sender[null] sent message of type "services.GitMetadata$GetAllVersions$"

### ISSUE THREAD

**Issue by nishanpatel** [salesforce/oss-request#49]
Hi James ,

I tried running this app in local as well as deployed to Heroku but in both the places I was getting below error,

**Ask timed out on [Actor[akka://application/user/$a#-1415981005]] after [15000 ms]. Sender[null] sent message of type "services.GitMetadata$GetAllVersions$"**

Thanks,
Nishan

**Comment by jamesward** [comment]
Thanks for reporting!  I'll investigate.

**Comment by jamesward** [comment]
BTW, did you see any other errors in the log?

**Comment by nishanpatel** [comment]
I can see below error log on my local console:


> [info] play.api.Play - Application started (Dev)
> [error] a.a.OneForOneStrategy - Invalid remote: origin
> org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
>         at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:251)
>         at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
>         at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
>         at services.GitMetadataActor.gitRepo$lzycompute(GitMetadata.scala:122)
>         at services.GitMetadataActor.gitRepo(GitMetadata.scala:82)
>         at services.GitMetadataActor.versions(GitMetadata.scala:148)
>         at services.GitMetadataActor$$anonfun$receive$1.applyOrElse(GitMetadata.scala:183)
>         at akka.actor.Actor.aroundReceive(Actor.scala:517)
>         at akka.actor.Actor.aroundReceive$(Actor.scala:515)
>         at services.GitMetadataActor.aroundReceive(GitMetadata.scala:61)
> Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: file:///C:/Users/npatel2/IdeaProjects/oss-request/: not found.
>         at org.eclipse.jgit.transport.TransportLocal$1.open(TransportLocal.java:132)
>         at org.eclipse.jgit.transport.TransportBundleFile$1.open(TransportBundleFile.java:107)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:553)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:429)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:308)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:277)
>         at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235)
>         at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
>         at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
>         at services.GitMetadataActor.gitRepo$lzycompute(GitMetadata.scala:122)
> [error] s.GitMetadataActor - Invalid remote: origin
> akka.actor.PreRestartException: akka://application/user/$a: exception in preRestart(class org.eclipse.jgit.api.errors.InvalidRemoteException, class services.GitMetadata$
> GetAllVersions$)
>         at akka.actor.PreRestartException$.apply(Actor.scala:210)
>         at akka.actor.dungeon.FaultHandling.$anonfun$faultRecreate$1(FaultHandling.scala:69)
>         at akka.actor.dungeon.FaultHandling.$anonfun$faultRecreate$1$adapted(FaultHandling.scala:68)
>         at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:303)
>         at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:298)
>         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
>         at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:68)
>         at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:55)
>         at akka.actor.ActorCell.faultRecreate(ActorCell.scala:433)
>         at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:528)
> Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
>         at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:251)
>         at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
>         at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
>         at services.GitMetadataActor.gitRepo$lzycompute(GitMetadata.scala:122)
>         at services.GitMetadataActor.gitRepo(GitMetadata.scala:82)
>         at services.GitMetadataActor.postStop(GitMetadata.scala:187)
>         at akka.actor.Actor.preRestart(Actor.scala:600)
>         at akka.actor.Actor.preRestart$(Actor.scala:595)
>         at services.GitMetadataActor.preRestart(GitMetadata.scala:61)
>         at akka.actor.Actor.aroundPreRestart(Actor.scala:544)
> Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: file:///C:/Users/npatel2/IdeaProjects/oss-request/: not found.
>         at org.eclipse.jgit.transport.TransportLocal$1.open(TransportLocal.java:132)
>         at org.eclipse.jgit.transport.TransportBundleFile$1.open(TransportBundleFile.java:107)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:553)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:429)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:308)
>         at org.eclipse.jgit.transport.Transport.open(Transport.java:277)
>         at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235)
>         at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
>         at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
>         at services.GitMetadataActor.gitRepo$lzycompute(GitMetadata.scala:122)

**Comment by jamesward** [comment]
Thanks!  That helps.  Looks like I'm making some assumptions in the local dev env.  And should make the error handling nicer.  I'll work on that.

In the meantime, if you want to get it working locally, you'll need to point it to a real git repo for the metadata.  The easiest way to do that is to run the app out of a git cloned repo.

**Comment by nishanpatel** [comment]
Thanks James, will try and let you know in case of any issue.
